version: '3'
services:
  web:
    build: .
    command: bash -c "bundle exec puma -p 3000"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - MAIL_TO=${MAIL_TO}
